[package]
name = "nfs-autoshare-daemon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ipnetwork = "0.20.0"
once_cell = "1.19.0"
mdns-sd = "0.10.4"
local-ip-address = "0.5.7"
gethostname = "0.4.3"